### ISSUE TITLE
add documentation for ROS installation process

### ISSUE THREAD

**Issue by minhnh** [mas-group/foundations_course#41]
Few of the points that I think ought to be documented in the ROS installation [README.md](https://github.com/mas-group/foundations_course/tree/master/content/ros/ROS%20Installation/README.md) or in the [installation script](https://github.com/mas-group/foundations_course/blob/master/content/ros/ROS%20Installation/ros_catkin_installer.sh):
* Why is the bugfix necessary for `stage`, and what's changed compared to the original. Are these changes needed in future stage versions?
* Why is `desktop-full` needed for installation. I don't think students need the full version even for AMR right?

At least these are not obvious to me. If somebody explains I can also make a pull request.

**Comment by argenos** [comment]
I think the original author is @tmetzl, not sure if he’ll TA this semester as well. Perhaps he can comment on it.

**Comment by tmetzl** [comment]
The stage fix is needed because of this:
https://github.com/rtv/Stage/issues/64
This bugfix is not in ROS Kinetic and therefor I included the changed stage.hh file.
The bugfix for KDL is needed since a few years because they did not include that in newer versions yet:
https://github.com/orocos/orocos_kinematics_dynamics/issues/48
The fix is by @alexander-hagg and was already needed when he was the TA together with Marcel.

I included desktop-full since when I wrote the installation script I did not have the time to identify which components are actually needed and which are not. 

I don't know who will be TA but I'll talk to Prof. Plöger about in on Monday.

**Comment by tmetzl** [comment]
There is another issue with the installation script.
For last semesters AMR course (SS18) I created the private HBRS-AMR organization. In there is the public AMR-Wiki (https://github.com/HBRS-AMR/AMR-Wiki).
This also includes the (now outdated) installation script together with a few FAQs and READMEs. Maintaining both installation scripts (here and there) will eventually cause problems because one will be outdated. 

I propose to either link to that Wiki or move the Wiki here so we don't have duplicates at different places.
What solution would you prefer?

**Comment by minhnh** [comment]
resolved with PR #46
